import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Audiowide } from 'next/font/google'
import Footer from "@/components/Footer";

const audiowide = Audiowide({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar/>
      <body className={`${audiowide.className} bg-[#01003D] text-white`}>
        {children}
      </body>
      <Footer/>
    </html>
  );
}
